### PR TITLE
Added Cordova sample :

### PR DESCRIPTION
**Pull request by pjeannet**
The Backend part is the same as MVC.Server, just changed the uri_redirect in startup.cs to target the app.
The MobileApp is built with Cordova and Ionic.

### CODE REVIEW

**Comment by kevinchalet** [comment]
Thanks! :clap: 

/cc @DovydasNavickas as a JS expert, do you wanna take a look? :smile:

**Comment by DovydasNavickas** [comment]
During weekend I can :)

**Comment by DovydasNavickas** [comment]
Ooook. I'm not Cordova specialist (i.e. never compiled an app with it), but...
What is [this](https://github.com/pierre-weceipt/AspNet.Security.OpenIdConnect.Samples/blob/13965f41bf89f50ef75039b86d30ca432a623a27/samples/Cordova/MobileApp/www/scripts/controllers/authController.js#L7) and [this](https://github.com/pierre-weceipt/AspNet.Security.OpenIdConnect.Samples/blob/13965f41bf89f50ef75039b86d30ca432a623a27/samples/Cordova/MobileApp/www/scripts/controllers/authController.js#L18)?

Also, I would move configuration (such as [this](https://github.com/pierre-weceipt/AspNet.Security.OpenIdConnect.Samples/blob/13965f41bf89f50ef75039b86d30ca432a623a27/samples/Cordova/MobileApp/www/scripts/services/authService.js#L4) and [URL from this](https://github.com/pierre-weceipt/AspNet.Security.OpenIdConnect.Samples/blob/13965f41bf89f50ef75039b86d30ca432a623a27/samples/Cordova/MobileApp/www/scripts/services/authService.js#L36)) out into a single file, e.g. `config.js` or sth, because having to change everything throughout the solution is not really helping with clarity.

A minor thing about different naming case [here](https://github.com/pierre-weceipt/AspNet.Security.OpenIdConnect.Samples/blob/13965f41bf89f50ef75039b86d30ca432a623a27/samples/Cordova/MobileApp/www/scripts/services/authService.js#L34) and [here](https://github.com/pierre-weceipt/AspNet.Security.OpenIdConnect.Samples/blob/13965f41bf89f50ef75039b86d30ca432a623a27/samples/Cordova/MobileApp/www/scripts/services/authService.js#L13)

Also [this](https://github.com/pierre-weceipt/AspNet.Security.OpenIdConnect.Samples/blob/13965f41bf89f50ef75039b86d30ca432a623a27/samples/Cordova/MobileApp/www/scripts/services/authService.js#L28-L32) and [this](https://github.com/pierre-weceipt/AspNet.Security.OpenIdConnect.Samples/blob/13965f41bf89f50ef75039b86d30ca432a623a27/samples/Cordova/MobileApp/www/scripts/services/authService.js#L62-L64) should not be in the middle of `authService.js` :smile: 

And a mistype in a `libraries` folder name [here](https://github.com/pierre-weceipt/AspNet.Security.OpenIdConnect.Samples/tree/13965f41bf89f50ef75039b86d30ca432a623a27/samples/Cordova/MobileApp/www/scripts) (or is it in French?).

Then there's a question whether to keep the dummy methods [here](https://github.com/pierre-weceipt/AspNet.Security.OpenIdConnect.Samples/blob/13965f41bf89f50ef75039b86d30ca432a623a27/samples/Cordova/MobileApp/www/scripts/index.js) and a dummy files [here](https://github.com/pierre-weceipt/AspNet.Security.OpenIdConnect.Samples/blob/13965f41bf89f50ef75039b86d30ca432a623a27/samples/Cordova/MobileApp/www/scripts/platformOverrides.js) and [here](https://github.com/pierre-weceipt/AspNet.Security.OpenIdConnect.Samples/tree/13965f41bf89f50ef75039b86d30ca432a623a27/samples/Cordova/MobileApp/www/css). These files with non-English comments do no good for the sample  :)

All in all, the sample looks OK and if it works, then there are only these minor things to fix. Apart from that, I'd say having everything written in English (including comments) is the most beneficial if you want to reach most people.

Thank you for the PR! :clap: :smile:

**Comment by pjeannet** [comment]
> Ooook. I'm not Cordova specialist (i.e. never compiled an app with it), but...
>  What is this and this?

I think it was to check if the user was not already authenticated and to avoid calling login function. However the button for login is hidden if user is authenticated so it can be remove. (TBH I think it was part of some code that I copy/pasted when I tried cordova projects)

> Also, I would move configuration (such as this and URL from this) out into a single file, e.g.  config.js  or sth, because having to change everything throughout the solution is not really helping with clarity.

As it was just a sample, I didn't want to add too much files, but I think we can add it in `router.js` file that needs a renaming like `init.js` as the angular app is initialized in it and there is no routing in this app!

> A minor thing about different naming case here and here

Will correct it!

> Also this and this should not be in the middle of  authService.js  :smile: 

I agree, I was lazy to put it somewhere else as it was a simple sample. Will correct it!

> And a mistype in a  libraries  folder name here (or is it in French?).

`Libraries` is just the plural for `Library`, it seems to me that it is valid English ;)

> Then there's a question whether to keep the dummy methods here and a dummy files here and here. These files with non-English comments do no good for the sample :)

These files are auto generated by VS Template and I did the huge mistake of instaling it in french, if I find time I will change it back to English. Anyway `index.js` and `index.css` can be removed, `platformOverride.js` gets regenerated each time (I need to check again though). I need to check again to remove the french comments from the templated parts.

**Comment by DovydasNavickas** [comment]
Awesome! Gonna wait for changes! :clap: 

And with `libraries`, yes, the word I wrote is proper English, a plural version of the word `library`. But if I see it correctly here:
image

It says `librairies` instead of `libraries` :smile: 
So, that would be the last change I'd recommend :clap: Good job! :smile:

**Comment by pjeannet** [comment]
> It says  librairies  instead of  libraries  :smile: 
>  So, that would be the last change I'd recommend :clap: Good job! :smile: 

Oups x)

**Comment by pjeannet** [comment]
Done!

**Comment by DovydasNavickas** [comment]
Nice! I think it's ready to merge :+1:

**Comment by kevinchalet** [comment]
Merci Pierre! :smile: 

Do you wanna squash your commits before I merge it?

**Comment by pjeannet** [comment]
Done :)

**Comment by kevinchalet** [comment]
Merged, thanks Pierre! :clap:

https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Samples/commit/95857c5c2e6f741d7b91b7867b102ec7acfe8aff

**Pull request closed without merging**
