### PR TITLE
docs(readme): create main readme and describe Mvc sample

### PR DESCRIPTION
**Pull request by BrainCrumbz**

### CODE REVIEW

**Comment by kevinchalet** [comment]
Looks fine, thanks! :clap: 

nit: could you please update the README to use the same "style" as the one we use for the other repos? (e.g https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/dev/README.md).

I think having at least the support/contributors/license sections is a must :smile:

**Comment by BrainCrumbz** [comment]
That is totally right. Initially the change was meant for a sub-directory readme, but then it moved to be the root readme: there it absolutely makes sense to complete with those sections.

**Comment by BrainCrumbz** [comment]
Hello there! What do you think about it, after adding those "standard" sections?

**Comment by kevinchalet** [comment]
Thanks for your contribution (and sorry for the delay)! :tada: 

Merged (with a few minor modifications): https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Samples/commit/71ca6995d8641a7912463147a8cc0f45a6dbdd44.

If you want to add a few words under the Cordova/SignalR samples nodes, feel free to submit a new PR :clap:

**Pull request closed without merging**
